Exclude tests from being run in jitpack because of javac error
Following error is thrown for

> java.lang.VerifyError: Inconsistent stackmap frames at branch target 121
2443.	Exception Details:
2444.	  Location:
2445.	    co/anitrend/arch/extension/util/time/SupportDateTimeUnit.<clinit>()V @110: goto
2446.	  Reason:
2447.	    Current frame's stack size doesn't match stackmap.